spring:

  config:
    import: classpath:application-secret.yml

  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
        use-new-id-generator-mappings: false
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImp



server:
  servlet:
    context-path: /api
  #Access logging
  tomcat:
    basedir: .                              # access log를 저장할 base directory 지정
    accesslog:
      enabled: true                         # access log 저장 여부 (default: false)
      directory: logs                       # access log를 저장할 상세 directory (base directory에 기반한) (default: logs)
      pattern: '%h %l %u %t "%r" %s %b %D'  # access log 출력 패턴
      prefix: access                        # access log 파일이름 prefix
      suffix: .log                          # access log 파일이름 suffix (확장자 포함)
      mbeanregistry: # 톰캣 메트릭을 모두 사용하려면 다음 옵션을 켜야하며, 옵션을 켜지 않으면 tomcat.session. 관련정보만 노출됩니다


logging:
  file:
    path: /home/ubuntu/log
  config: classpath:log4j2.yml
  level:
    com.zaxxer.hikari.HikariConfig: WARN
    com.zaxxer.hikari: WARN

#debug: true


management:
  endpoints:
    web:
      exposure:
        include: "*" #  이 설정은 모든 Actuator 엔드포인트를 외부에 노출
      base-path: /api/actuator # Actuator 엔드포인트의 기본 경로 지정
  server:
    port: 9090 # Actuator 엔드포인트가 서비스될 서버의 포트