spring:

  config:
    import: classpath:application-secret.yml

  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
        use-new-id-generator-mappings: false
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImp

  # Security OAuth
  security:
    oauth2.client:
      registration:
        kakao:
          clientId: '2b3e53a89d2794b4afa3cbed27c2ad30'
          clientSecret: 'GGxnBUprx4NVmo84JKIzuaLvhIS9Itxf'
          clientAuthenticationMethod: client_secret_post
          authorizationGrantType: authorization_code
          redirectUri: "https://j10d109.p.ssafy.io/api/{action}/oauth2/code/{registrationId}"
          #redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
          #            - account_email
          #            - age_range
          #            - gender
          #            - birthday
          clientName: Kakao
      # Provider 설정
      provider:
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

server:
  servlet:
    context-path: /api
  #Access logging
  tomcat:
    basedir: .                              # access log를 저장할 base directory 지정
    accesslog:
      enabled: true                         # access log 저장 여부 (default: false)
      directory: logs                       # access log를 저장할 상세 directory (base directory에 기반한) (default: logs)
      pattern: '%h %l %u %t "%r" %s %b %D'  # access log 출력 패턴
      prefix: access                        # access log 파일이름 prefix
      suffix: .log                          # access log 파일이름 suffix (확장자 포함)

logging:
  file:
    path: /home/ubuntu/log
  config: classpath:log4j2.yml
  level:
    com.zaxxer.hikari.HikariConfig: WARN
    com.zaxxer.hikari: WARN

#debug: true